### ISSUE TITLE
AttributeError: 'Future' object has no attribute '_waiters'

### ISSUE THREAD

**Issue by meetmangukiya** [talkiq/gcloud-aio#117]
```
Exception in thread Thread-OnRpcTerminated:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 491, in close
    callback(self, reason)
  File ".../google/cloud/pubsub_v1/subscriber/futures.py", line 39, in _on_close_callback
    self.set_exception(result)
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 531, in set_exception
    for waiter in self._waiters:
AttributeError: 'Future' object has no attribute '_waiters'
```

**Comment by meetmangukiya** [comment]
Need to add _waiters attribute to the wrapped future

**Comment by meetmangukiya** [comment]
Created a PR : https://github.com/talkiq/gcloud-aio/pull/118

**Comment by TheKevJames** [comment]
Thanks again for the fix!
