### ISSUE TITLE
KeyError: 'values'

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#321]
Hi, team!

I'm trying to play with aio version of this library and get errors.

# Environment:
- python version: `3.9.0`
- pip version: `21.0.1`
- gcloud-aio-datastore version: `6.2.1`

# Example:
```
import asyncio

from gcloud.aio.datastore import Datastore, Query


async def main():
    db = Datastore('kitchenhub-app-sandbox', '/tmp/credentials.json')
    query = Query(kind='Restaurant')
    results = await db.runQuery(query)
    print(len(results))


if __name__ == '__main__':
    asyncio.run(main())
```

# Traceback
```
(aiodatastore) ➜  aiodatastore python main.py
Traceback (most recent call last):
  File "/Users/max/projects/aiodatastore/main.py", line 14, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/max/projects/aiodatastore/main.py", line 9, in main
    results = await db.runQuery(query)
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/datastore.py", line 366, in runQuery
    return self.query_result_batch_kind.from_repr(data['batch'])
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/query.py", line 184, in from_repr
    entity_results = [cls.entity_result_kind.from_repr(er)
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/query.py", line 184, in <listcomp>
    entity_results = [cls.entity_result_kind.from_repr(er)
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/entity.py", line 70, in from_repr
    return cls(cls.entity_kind.from_repr(data['entity']),
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/entity.py", line 38, in from_repr
    return cls(key, data.get('properties'))
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/entity.py", line 17, in __init__
    self.properties = {k: self.value_kind.from_repr(v).value
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/entity.py", line 17, in <dictcomp>
    self.properties = {k: self.value_kind.from_repr(v).value
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/value.py", line 46, in from_repr
    value = value_type.from_repr(data[json_key])
  File "/Users/max/venv/aiodatastore/lib/python3.9/site-packages/gcloud/aio/datastore/array.py", line 34, in from_repr
    return cls([value.Value.from_repr(x) for x in data['values']])
KeyError: 'values'
```

Please, help.

**Comment by KevinGDialpad** [comment]
Interesting. According to the [API docs for ArrayValue](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/runQuery#ArrayValue), the JSON you receive should have that key.

Would you be able to run the query in the "Try this API" pane in the link above, and paste the query and the response here?

I suspect that it is failing on a Restaurant entity with an empty array property, where the API simply returns `{}` instead of `{ "values": [] }` as the representation of that property. If my guess is correct then we simply need to handle that edge case in `Array.from_repr()`.

**Comment by umax** [comment]
hi, @KevinGDialpad 
I tried use "Try this API" and run the same query as in my script - it works. So, I think the issue is in library.

**Comment by KevinGDialpad** [comment]
Can you paste the JSON that the API returns?

**Comment by umax** [comment]
I have an entity in database with `users` property. When value of this property was empty list - library raise error. I changed the value to None and library start working. But I think it's a bug because empty list is a valid value for property.

**Comment by KevinGDialpad** [comment]
> But I think it's a bug because empty list is a valid value for property.

I know; that's why I'm asking what JSON the API returns in that case - so the library can parse it properly.

**Comment by umax** [comment]
@KevinGDialpad this is JSON result when `user_id` property is set to empty list:
```
{
  "batch": {
    "entityResultType": "FULL",
    "entityResults": [
      {
        "entity": {
          "key": {
            "partitionId": {
              "projectId": "XXXXXXX"
            },
            "path": [
              {
                "kind": "Restaurant",
                "id": "5688701843144704"
              }
            ]
          },
          "properties": {
            "updated_at": {
              "nullValue": null
            },
            "play_new_order_sound": {
              "booleanValue": true,
              "excludeFromIndexes": true
            },
            "print_modifier_on_kitchen_receipt": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "proxy_restaurant": {
              "booleanValue": false
            },
            "proxy_restaurant_id": {
              "nullValue": null
            },
            "restaurant_lon": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "auto_accept_cooking_time": {
              "integerValue": "20",
              "excludeFromIndexes": true
            },
            "created_at": {
              "timestampValue": "2021-05-07T17:28:41.945035Z"
            },
            "website_orders_confirm_sms_text": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "restaurant_city": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "send_confirm_sms_for_website_orders": {
              "booleanValue": false
            },
            "restaurant_delivery_time": {
              "integerValue": "30",
              "excludeFromIndexes": true
            },
            "has_printer": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "restaurant_email": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "split_kitchen_receipt": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "restaurant_lat": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "restaurant_state": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "print_receipt_number": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "subscription_status": {
              "stringValue": "onboarding"
            },
            "restaurant_website": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "print_modifier_on_front_receipt": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "show_new_order_notification": {
              "booleanValue": true,
              "excludeFromIndexes": true
            },
            "subscription_plan": {
              "stringValue": "aggregation"
            },
            "restaurant_id": {
              "stringValue": "4b557b20-25b9-4526-906d-f41415b13ac5"
            },
            "pos_enabled": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "restaurant_timezone": {
              "stringValue": "America/New_York",
              "excludeFromIndexes": true
            },
            "user_id": {
              "arrayValue": {}
            },
            "restaurant_phone_number": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "print_recipe_on_kitchen_receipt": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "restaurant_street": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "trial_period_days": {
              "integerValue": "14",
              "excludeFromIndexes": true
            },
            "restaurant_zip": {
              "nullValue": null,
              "excludeFromIndexes": true
            },
            "restaurant_name": {
              "stringValue": "testrest"
            },
            "auto_accept_enabled": {
              "booleanValue": false,
              "excludeFromIndexes": true
            },
            "ask_for_delivery_by_postmates": {
              "booleanValue": false
            },
            "show_option_modifier": {
              "booleanValue": true,
              "excludeFromIndexes": true
            }
          }
        },
        "cursor": "CjkSM2oYc35raXRjaGVuaHViLWFwcC1zYW5kYm94chcLEgpSZXN0YXVyYW50GICA4OSBu40KDBgAIAA=",
        "version": "1620408522013000"
      }
    ],
    "endCursor": "CjkSM2oYc35raXRjaGVuaHViLWFwcC1zYW5kYm94chcLEgpSZXN0YXVyYW50GICA4KSM8Z0KDBgAIAA=",
    "moreResults": "NO_MORE_RESULTS"
  }
}
```

**Comment by umax** [comment]
array.py:

`def from_repr(cls, data: Dict[str, Any]) -> 'Array'`

I think it should be:

`def from_repr(cls, data: Dict[str, Any]) -> Array`

**Comment by umax** [comment]
The problem is that aio library is not supporting list values. With `google.cloud` library I was able to assign lists to attributes, with this library I get error that list values is not supported.

**Comment by TheKevJames** [comment]
Hi @umax -- thanks for the bug report! I've just fixed up the default value handling and will be releasing `gcloud-aio-datastore` v6.2.2 shortly with the fix. Please let us know if you have any follow-up issues!

With respect to the type hint, the `'Array'` form is used as a form of lazy evaluation to avoid infinite reference loops in earlier versions of Python. Version 3.8, I believe, supports lazy evaluation of type hints, but prior to that point you need to use string versions of class names to avoid reference errors. They should evaluate the same way in any type checker :)

**Comment by umax** [comment]
hi, @TheKevJames! Thank you! I will test v6.2.2 with my codebase. Btw, I'm migrating all my services from sync datastore library to async one. So, it's a good chance to test all things.
