### ISSUE TITLE
Entity representation error

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#381]
Hi, team!

Let me describe the problem. I have an entity, some of its fields should not be indexed. That's why on entity creation I do something like this for fields declaration:
```
props = {
    'field1': Value(long_string_value, exclude_from_indexes=True),
    'field2': ...,
}
<create call>
```

and this when update an entity:
```
for key, value in update_data.items():
    if key in non_indexed_fields:
        entity.properties[key] = Value(value, exclude_from_indexes=True)
<update call>
```
All works fine! Now I want to cache an entity in Redis, for example. So, I need to get a text representation for an entity. I call:
```
entity.repr()
```
and get this error:
```
self = <[NotImplementedError("<class 'gcloud.aio.datastore.value.Value'> is not a supported value type (any of: {<class 'bool...loud.aio.datastore.entity.Entity'>: <TypeName.ENTITY: 'entityValue'>})") raised in repr()] Value object at 0x10749d250>
value = {'excludeFromIndexes': True, 'stringValue': '{"uuid":"123"}'}

    def _infer_type(self, value: Any) -> TypeName:
        odd_strings = {'newstr', 'unicode'}
        kind = str if value.__class__.__name__ in odd_strings else type(value)
        supported_types = self._get_supported_types()

        try:
>           return supported_types[kind]
E           KeyError: <class 'gcloud.aio.datastore.value.Value'>

.../lib/python3.9/site-packages/gcloud/aio/datastore/value.py:85: KeyError

.../orders.py:428: in handle_out_the_door_order
    await cache.set_order(order_data['uuid'], db_order)
.../cache.py:125: in set_order
    value = json.dumps(order.to_repr())
.../lib/python3.9/site-packages/gcloud/aio/datastore/entity.py:43: in to_repr
    'properties': {k: self.value_kind(v).to_repr()
.../lib/python3.9/site-packages/gcloud/aio/datastore/entity.py:43: in <dictcomp>
    'properties': {k: self.value_kind(v).to_repr()
.../lib/python3.9/site-packages/gcloud/aio/datastore/value.py:64: in to_repr
    value_type = self._infer_type(self.value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[NotImplementedError("<class 'gcloud.aio.datastore.value.Value'> is not a supported value type (any of: {<class 'bool...loud.aio.datastore.entity.Entity'>: <TypeName.ENTITY: 'entityValue'>})") raised in repr()] Value object at 0x1030f71f0>
value = {'excludeFromIndexes': True, 'stringValue': '{"uuid":"123"}'}

    def _infer_type(self, value: Any) -> TypeName:
        odd_strings = {'newstr', 'unicode'}
        kind = str if value.__class__.__name__ in odd_strings else type(value)
        supported_types = self._get_supported_types()

        try:
            return supported_types[kind]
        except KeyError:
>           raise NotImplementedError(  # pylint: disable=raise-missing-from
                '{} is not a supported value type (any of: '
                '{})'.format(kind, supported_types))
E           NotImplementedError: <class 'gcloud.aio.datastore.value.Value'> is not a supported value type (any of: {<class 'bool'>: <TypeName.BOOLEAN: 'booleanValue'>, <class 'bytes'>: <TypeName.BLOB: 'blobValue'>, <class 'datetime.datetime'>: <TypeName.TIMESTAMP: 'timestampValue'>, <class 'float'>: <TypeName.DOUBLE: 'doubleValue'>, <class 'int'>: <TypeName.INTEGER: 'integerValue'>, <class 'gcloud.aio.datastore.lat_lng.LatLng'>: <TypeName.GEOPOINT: 'geoPointValue'>, <class 'str'>: <TypeName.STRING: 'stringValue'>, <class 'NoneType'>: <TypeName.NULL: 'nullValue'>, <class 'gcloud.aio.datastore.key.Key'>: <TypeName.KEY: 'keyValue'>, <class 'gcloud.aio.datastore.array.Array'>: <TypeName.ARRAY: 'arrayValue'>, <class 'gcloud.aio.datastore.entity.Entity'>: <TypeName.ENTITY: 'entityValue'>})

.../lib/python3.9/site-packages/gcloud/aio/datastore/value.py:87: NotImplementedError
```

**Comment by umax** [comment]
@TheKevJames hi! Please review this issue. Is it library bug or I do something wrong? Thank you!

**Comment by TheKevJames** [comment]
@umax sorry for the incredibly late triage on this.

This is indeed a usage issue; the issue here is that the `Entity` class expects to be storing the data directly in its `properties` attribute rather than `Value` objects. Its constructor knows how to convert between the two, so for example:
```
>>> entity = Entity(key=None, properties={})
>>> entity.properties['foo'] = Value('asdfasdfasdf',  exclude_from_indexes=True)
>>> entity.to_repr()
Traceback (most recent call last):
  File "/Users/kevin/src/talkiq/gcloud-aio/datastore/gcloud/aio/datastore/value.py", line 85, in _infer_type
    return supported_types[kind]
KeyError: <class 'gcloud.aio.datastore.value.Value'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin/src/talkiq/gcloud-aio/datastore/gcloud/aio/datastore/entity.py", line 44, in to_repr
    for k, v in self.properties.items()},
  File "/Users/kevin/src/talkiq/gcloud-aio/datastore/gcloud/aio/datastore/entity.py", line 44, in <dictcomp>
    for k, v in self.properties.items()},
  File "/Users/kevin/src/talkiq/gcloud-aio/datastore/gcloud/aio/datastore/value.py", line 64, in to_repr
    value_type = self._infer_type(self.value)
  File "/Users/kevin/src/talkiq/gcloud-aio/datastore/gcloud/aio/datastore/value.py", line 89, in _infer_type
    '{})'.format(kind, supported_types))
NotImplementedError: <class 'gcloud.aio.datastore.value.Value'> is not a supported value type (any of: {<class 'bool'>: <TypeName.BOOLEAN: 'booleanValue'>, <class 'bytes'>: <TypeName.BLOB: 'blobValue'>, <class 'datetime.datetime'>: <TypeName.TIMESTAMP: 'timestampValue'>, <class 'float'>: <TypeName.DOUBLE: 'doubleValue'>, <class 'int'>: <TypeName.INTEGER: 'integerValue'>, <class 'gcloud.aio.datastore.lat_lng.LatLng'>: <TypeName.GEOPOINT: 'geoPointValue'>, <class 'str'>: <TypeName.STRING: 'stringValue'>, <class 'NoneType'>: <TypeName.NULL: 'nullValue'>, <class 'gcloud.aio.datastore.key.Key'>: <TypeName.KEY: 'keyValue'>, <class 'gcloud.aio.datastore.array.Array'>: <TypeName.ARRAY: 'arrayValue'>, <class 'gcloud.aio.datastore.entity.Entity'>: <TypeName.ENTITY: 'entityValue'>})
```
but correctly
```
>>> entity = Entity(key=None, properties={'foo': Value('asdfasdfasdf',  exclude_from_indexes=True).to_repr()})
>>> entity.to_repr()
{'key': None, 'properties': {'foo': {'excludeFromIndexes': False, 'stringValue': 'asdfasdfasdf'}}}
```

I'd generally urge you to make use of the Entity constructor here, but if you do need to override rather than modify the properties, you could do:
```python
>>> entity = Entity(key=None, properties={})
>>> entity.properties['foo'] = Value('asdfasdfasdf',  exclude_from_indexes=True).value
>>> entity.to_repr()
{'key': None, 'properties': {'foo': {'excludeFromIndexes': False, 'stringValue': 'asdfasdfasdf'}}}
```

(note the trailing call to the `.value` property on the `Value` object)

**Comment by umax** [comment]
hi, @TheKevJames 

Thank you for explanation, now it's clear for me how to use it.
