### ISSUE TITLE
RuntimeError: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by astariul** [talkiq/gcloud-aio#424]
Inside a FastAPI app, I try to upload a file to a GCP bucket, but I'm having the following error :

```
Task exception was never retrieved
future: <Task finished coro=<_save_audio_in_bucket() done, defined at /home/astariul/karma/karma/v0.py:195> exception=RuntimeError('Timeout context manager should be used inside a task')>
Traceback (most recent call last):
  File "/home/astariul/karma/karma/v0.py", line 198, in _save_audio_in_bucket
    await async_client.upload_from_filename(config.bucket, dest, audio_file)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/storage/storage.py", line 371, in upload_from_filename
    **kwargs)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/storage/storage.py", line 337, in upload
    headers.update(await self._headers())
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/storage/storage.py", line 142, in _headers
    token = await self.token.get()
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/auth/token.py", line 144, in get
    await self.ensure_token()
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/auth/token.py", line 154, in ensure_token
    await self.acquiring
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/auth/token.py", line 216, in acquire_access_token
    resp = await self._refresh_service_account(timeout=timeout)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/auth/token.py", line 206, in _refresh_service_account
    timeout=timeout)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/gcloud/aio/auth/session.py", line 125, in post
    timeout=timeout_, params=params)
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/aiohttp/client.py", line 448, in _request
    with timer:
  File "/home/astariul/miniconda3/envs/karma/lib/python3.7/site-packages/aiohttp/helpers.py", line 636, in __enter__
    "Timeout context manager should be used " "inside a task"
RuntimeError: Timeout context manager should be used inside a task
```

I must be doing something wrong because when I initiate the client from the REPL (for debugging) and try to upload the file, it works perfectly (and fast, less than a second, so the timeout shouldn't be an issue).

---

I've been searching for hours now but I can't make it work... Any idea what I'm doing wrong ? Is there any consideration when working with FastAPI ?

**Comment by TheKevJames** [comment]
Huh, that stack trace is a bit confusing -- it sure looks like you've spawned a task and the context manager is being used within. We've also not seen any other reports of issues within FastAPI in particular, though there could certainly be something we missed! Could you share a reproduction case so we could debug further?

**Comment by astariul** [comment]
Thank you for your answer @TheKevJames !

I could narrow down the issue to this code snippet :

```python
import os
import asyncio

import uvicorn
from fastapi import FastAPI, UploadFile, File
from gcloud.aio.storage import Storage


app = FastAPI()
async_client = Storage()


async def _save_in_bucket(f):
    # Upload the file
    dest = os.path.join("test", os.path.basename(f))
    await async_client.upload_from_filename("shush_bucket", dest, f)


@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    with open("tmp.tmp", "wb") as f:
        f.write(file.file.read())
    asyncio.create_task(_save_in_bucket("tmp.tmp"))
    return {}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

In this code, the user can just send a file and the code is supposed to save it in the GCP bucket. But I have the error mentioned earlier.

---

As you can see, I "fire-n-forget", but I also tried without fire-n-forget :

```python
@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    with open("tmp.tmp", "wb") as f:
        f.write(file.file.read())
    await _save_in_bucket("tmp.tmp")
    return {}
```

And I have the same error...

---

And here is the code for synchronous version (using `google-cloud-storage` library) :

```python
import os
import asyncio

import uvicorn
from fastapi import FastAPI, UploadFile, File
from google.cloud import storage


app = FastAPI()
storage_client = storage.Client()
bucket = storage_client.bucket("shush_bucket")


def _save_in_bucket(f):
    # Upload the file
    dest = os.path.join("test", os.path.basename(f))
    bucket.blob(dest).upload_from_filename(f)


@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    with open("tmp.tmp", "wb") as f:
        f.write(file.file.read())
    _save_in_bucket("tmp.tmp")
    return {}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

This version works perfectly fine, but of course it's slower...

---

Any idea what I'm doing wrong ? Or can you reproduce the issue on your side ?

**Comment by astariul** [comment]
@TheKevJames Thank you !!!

You are right on point, if I call `Storage()` after FastAPI starts, then it works !

Here is the full script for FastAPI :

```python
import os
import asyncio

import uvicorn
from fastapi import FastAPI, UploadFile, File
from gcloud.aio.storage import Storage


app = FastAPI()
ctx = {}


@app.on_event("startup")
async def startup_event():
    ctx["async_client"] = Storage()


async def _save_in_bucket(f):
    # Upload the file
    dest = os.path.join("test", os.path.basename(f))
    await ctx["async_client"].upload_from_filename("shush_bucket", dest, f)


@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    with open("tmp.tmp", "wb") as f:
        f.write(file.file.read())
    asyncio.create_task(_save_in_bucket("tmp.tmp"))
    return {}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

---

Thanks again ! I spent a lot of time and I gave up using async gcloud because of this issue, but now it's fixed !! Awesome @TheKevJames !
