### ISSUE TITLE
acquiring token host resolver issue

### ISSUE THREAD

**Issue by mrkiril** [talkiq/gcloud-aio#472]
I have aiohttp 3.8.1 and latest version of all library

1. gcloud-aio-storage==7.0.1
2. gcloud-aio-pubsub==5.0.0

aiohttp raise asyncio.CancelledError when they can`t host resolved, and as i see this error did not catch in any other place above.
So have anybody any idea about this situation ?
Is this ok or not ?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/auth/token.py", line 216, in acquire_access_token
    resp = await self._refresh_service_account(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/auth/token.py", line 204, in _refresh_service_account
    resp: Response = await self.session.post(self.token_uri, data=payload,
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/auth/session.py", line 134, in post
    resp = await self.session.post(url, data=data, headers=headers,
  File "/usr/local/lib/python3.10/site-packages/aiohttp_retry/client.py", line 98, in __aenter__
    return await self._do_request()
  File "/usr/local/lib/python3.10/site-packages/aiohttp_retry/client.py", line 71, in _do_request
    response: ClientResponse = await self._request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/views_content.py", line 89, in post
    url = await self.service_gcloud.get_signed_url(user_id, extension=data.extension)
  File "/app/utils/decorators.py", line 45, in wrapped
    return await func(this, *args, **kwargs)
  File "/app/bl/bl_google_cloud.py", line 209, in get_signed_url
    await self.storage.upload(
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/storage/storage.py", line 337, in upload
    headers.update(await self._headers())
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/storage/storage.py", line 142, in _headers
    token = await self.token.get()
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/auth/token.py", line 144, in get
    await self.ensure_token()
  File "/usr/local/lib/python3.10/site-packages/gcloud/aio/auth/token.py", line 149, in ensure_token
    await self.acquiring
asyncio.exceptions.CancelledError
```

**Comment by TheKevJames** [comment]
Looks like this relates to #500, which revealed that a future cancellation can get stuck in a loop. Once that gets resolved in the next release, this should be just fine: a future getting cancelled should now "do the right thing".

Thanks for the report!

**Comment by mrkiril** [comment]
thnk a lot 🚀
